### ISSUE TITLE
Remove getTeamManagersCount() method in TeamRoleService

### ISSUE THREAD

**Issue by marcinadd** [marcinadd/projecty-web#11]
Use countBy in TeamRoleRepository instead

**Comment by zunairaShafiq** [comment]
Hi I wanted to solve this would you please tell me the process i am the first time contributor.

**Comment by marcinadd** [comment]
TeamRoleService has method getTeamRolesWhereManager()  which can be replaced by countBy… method in TeamRoleRepository, same as in ProjectRoleRepository for example.

**Comment by zunairaShafiq** [comment]
so you want me to remove private int getTeamManagersCount(Team team) method from TeamRoleService and create a method int countByTeamAndName(Team team, TeamRoles name); in TeamRoleRepository class? 
is that right if yes than please guide me how create branch and than pull request. 

Thanks in advance

**Comment by marcinadd** [comment]
Yes. You're right. Read something about contributing.

**Comment by zunairaShafiq** [comment]
I have created a pull request for this issue. please review thanks
