### ISSUE TITLE
Add Domain

### ISSUE THREAD

**Issue by marcinadd** [marcinadd/projecty-web#12]
- In domain users cannot interact with other users outside domain

- Domain admin can bulk add users, remove them, set them admins; create in-domain teams

**Comment by didaRatsimba** [comment]
@marcinadd  I would like to work on this but I need more informations about what "domain" is meant to be

**Comment by marcinadd** [comment]
My idea is to create a separate group called domain. Users from domain can't communicate to users outside domain, can't be added to a project, can't be assigned to a task etc. Domain admin can create users, manage their rights, create teams. Something higher in a hierarchy like team.

**Comment by Neha-Rathore17** [comment]
@marcinadd I would like to contribute to the project. Is it still opened?

**Comment by marcinadd** [comment]
@Neha-Rathore17 Yes, it is.

**Comment by sgarg5794** [comment]
@marcinadd I want to work on this issue , Can you tell me brief about what needs to be done, Do we have to create a new web service or what ?

**Comment by marcinadd** [comment]
@sgarg5794 No, it is abandoned feature for now.
