### ISSUE TITLE
Failing test case givenRequestOnDownloadFile_shouldReturnFileToDownload

### ISSUE THREAD

**Issue by Anirban-1** [marcinadd/projecty-web#22]
Following test case is failing:
MessageControllerTests -> givenRequestOnDownloadFile_shouldReturnFileToDownload

**Comment by Anirban-1** [comment]
@marcinadd I want to start working on this project, I have created a separate branch and fixed the test case. But I am not allowed to push the changes. Can you help me out!

**Comment by marcinadd** [comment]
You have to fork my repo and push your changes to your fork, then create a pull request.

**Comment by anirban-a** [comment]
@marcinadd sorry that "Anirban-1" was my other account and I don't want to proceed working with that, I will be using this one only. But I don't have the permission granted to push the changes it seems for any of the accounts

**Comment by marcinadd** [comment]
You won't have permission to direct push to my repository. Read about "forks" and "pull requests" in GitHub Guides.

**Comment by anirban-a** [comment]
oh ok got it! Thanks, I have raised a pull request, please do review and let me know
