### ISSUE TITLE
gradle tasks jar

### ISSUE THREAD

**Issue by david81brs** [marcinadd/projecty-web#24]
> No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
  Possible solutions: asVersionComparator()

**Comment by marcinadd** [comment]
Strange I don't have such issues. Try to remove nebula lint from build.gradle

**Comment by david81brs** [comment]
Worked after removing
`plugins {
     id 'org.springframework.boot' version '2.1.7.RELEASE'
    id 'java'
    **id 'nebula.lint' version '6.1.4'**
 }

apply plugin: 'io.spring.dependency-management'
**apply plugin: 'nebula.lint'**
**gradleLint.rules = ['all-dependency']**
`

**Comment by marcinadd** [comment]
Fixed
