### ISSUE TITLE
Fix CI fail to run

### ISSUE THREAD

**Issue by marcinadd** [marcinadd/projecty-web#28]

**Comment by marcinadd** [comment]
CI Fail to run in 4 test cases in MessageControllerTests

**Comment by JasonSarwar** [comment]
Can I try to fix the tests?

**Comment by marcinadd** [comment]
Yes, of course.

**Comment by JasonSarwar** [comment]
I'm having a bit of a hard time, in case anyone else wants to try.

**Comment by ChrisCurl** [comment]
I will take a look at this.

**Comment by ChrisCurl** [comment]
Actually I have no idea how to setup the database, I'm a noob. Sorry about that.

**Comment by marcinadd** [comment]
First of all you have to install MySQL server. Then create a database and user with full access to this database. Invoke `USE your_database_name` and copy code from README. Go to application-development.properties and set your credentials. Now should works.

**Comment by allanmoso** [comment]
@marcinadd  I tried to look into this.   I can't seem to reproduce the failing tests. The tests pass for me.   I uncommented all the commented out tests.

**Comment by allanmoso** [comment]
OK. I see the issues now. I had to create a pull request to run the CI build. It passed locally.

**Comment by kacperkoza** [comment]
@marcinadd I can dockerize your application - you would avoid setting up the environment manually.

**Comment by marcinadd** [comment]
@kacperkoza Ok, Just create new issue.
