### ISSUE TITLE
Add option to delete message

### ISSUE THREAD

**Issue by marcinadd** [marcinadd/projecty-web#35]

**Comment by fokion** [comment]
I can give it a go

**Comment by marcinadd** [comment]
Ok. But don't forget that deleted message should be only for one user. I mean if user A deletes a message, user B should still have it.

**Comment by fokion** [comment]
I have started implementing it , by having a new table called associations where you associate a message with a user. When you create a new message you create new entries in the associations table where you have the user , the message and an id as an index ( so by creating a message you create an entry for the sender and one for the receiver) . You can now filter your messages that you get from the server based on this table ( so we hide  the messages you deleted from your view)

**Comment by marcinadd** [comment]
Ok idea.
```
  public void deleteMessageForUser(Message messageToBeDeleted, User user){
        Optional<Association> messageOptional = associationRepository.findByUser(user).stream()
                .filter(association -> messageToBeDeleted.equals(association.getMessage()))
                .findFirst();
        messageOptional.ifPresent(association -> associationRepository.delete(association));
    }
}
```
I regard that better option is to use findByUserAndMessage(), it isn't?

**Comment by marcinadd** [comment]
No problem. If you have any suggestions or enhancements just open a new issue.

**Comment by fokion** [comment]
#37

**Comment by marcinadd** [comment]
Ok. I'll look at it tomorrow.
