### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by marcinadd** [marcinadd/projecty-web#40]
User should get notifications; for example „You have been added to the project XYZ”.
Sample suggestion:

- Create Notification entity with User, timestamp and message code (for internationalisation)
- Create NotificationRepository
- Create NotificationController with getAllNotifications(), deleteAllNotifications()…

**Comment by acodebreaker** [comment]
can i take this up ?

**Comment by marcinadd** [comment]
Yes, of course.

**Comment by AtulSingh-Emyre** [comment]
Is the issue open for taking up?

**Comment by marcinadd** [comment]
@AtulSingh-Emyre Yes, it is.

**Comment by Sountastic** [comment]
If I want to take this one should I just assign myself here or should I wait for confirmation that is still free to take? ;)

**Comment by marcinadd** [comment]
@Sountastic Yeah. It's still free to take. There were some people who tried to do this but they didn't succeed. You will be assigned to this issue by me if you make any progress.

**Comment by charlygg** [comment]
Hi, Is the Issue open to new contributors?

**Comment by marcinadd** [comment]
@charlygg Yes, sure. However, it might be harder than it looks especially for beginners.

**Comment by Kasamel** [comment]
Hi, i need before start coding say that i take this issue or i can do it without it?:)

If it possible i want to take this issue:)

**Comment by marcinadd** [comment]
@Kasamel Sorry but I have already started working on this issue. There is a branch "notifications" which I created yesterday.
Due to higher traffic on this repo, I will try to create some other issues with features to implement. Or maybe you have your own ideas?
Check this repo in a few days there will probably be some issues to take up.
