### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by JBetts97** [marcinadd/projecty-web#58]
Hello,

Nice to meet you all, and hope you are well.

I have followed the docker steps to get the development build up and running however I am coming across some issues with the MySQL Database. I successfully signed-up as a user, however when I go to sign-in I get the following error message in my docker terminal window:

![image](https://user-images.githubusercontent.com/38386086/80992869-0e70bd80-8e32-11ea-94c6-7a7f0596ede1.png)

When I explore mySQL database using the oracle "MySQL Workbench" software, I can't see any issues with the DB setup:
![image](https://user-images.githubusercontent.com/38386086/80993122-70312780-8e32-11ea-935f-395b12849a88.png)

I am thinking that when I run the docker command "docker-compose up", the database is not found by docker. When I run the docker command with the database already started up, I get this error message:
![image](https://user-images.githubusercontent.com/38386086/80993420-f0578d00-8e32-11ea-8180-a8419e13ca7f.png)

Is my docker session, and mySQL database not allowed to be using the same port?

Kindest Regards,
Joseph

**Comment by marcinadd** [comment]
Sorry for late reply. I haven't get any notification about new issue. I will take a look at it tomorrow.

**Comment by JBetts97** [comment]
No problem. Thank you.

**Comment by marcinadd** [comment]
Ok issues have been fixed. I will fix tests tomorrow. Here is my comment about your issue:
This app uses flyway as a migration tool and contributor who implemented it forgot to add version information to gradle.build. There was probably a major update of flyway and app cannot detect a migration and perform it so there weren't necessary tables for storing OAuth tokens. Now it's also an obsolete solution. It's better to use Keycloak.

> Is my docker session, and MySQL database not allowed to be using the same port?

Check docker-compose.yaml file. Database container is bound to 3306 port so you cannot run other application on port 3306 on your pc. Of course, you can change it to for example 3307 and container will be running on 3307 etc.

Thanks for your contribution.
Give me back info if the issue has been fixed for you
Marcin

**Comment by JBetts97** [comment]
Thank you @marcinadd this has resolved my issue, and I am now able to login using the front-end website.

Kindest Regards,
Joseph
