### ISSUE TITLE
Making the development environment ready to use for developers.

### ISSUE THREAD

**Issue by himanshugoyal1065** [marcinadd/projecty-web#65]
I recently checked out the rest2.0 branch. Setting up the development environment took me some time and we should eradicate this issue.
The following problems which I saw:
1. There is a missing dialect for MySQL.
2. I see this typo - https://github.com/marcinadd/projecty-web/blob/b572a6ef876b379303e4c6a10725d10b2403f1c2/src/main/resources/application-development.properties#L9

Can you confirm are these really an issue or it was done intentionally?

I have worked on eradicating them and can create a PR if someone approves it.

**Comment by marcinadd** [comment]
1. You are right, but for me, it's working just without specifying dialect, but I agree that it should be added like in docker configuration.
2. It was done intentionally I think. When you uncomment this line output there is too much output in the console. When you press CTRL + / in IDEA in properties file it will comment lines with "; ". But. Yes, when we comment on all lines with "#" this should also be commented with "#".
Yes, you can create PR. I will approve it.
