### ISSUE TITLE
Refactor RestController Responses from POJO to Springs ResponseEntity

### ISSUE THREAD

**Issue by FlorianKrammel** [marcinadd/projecty-web#71]
Currently the response of a request returns a POJO. You can do this in a more flexible way with `public ResponseEntity<MyType>` and `return ResponseEntitiy.of(object)`.

> `ResponseEntity<T>` represents the entire HTTP response. Besides the body, its API allows you to set headers and a status code to the response.
> 
> Returning just a bean is fine but doesn't give you much flexibility: In the future, if you need to add a header to the response or modify the status code, for example, you need to change the method return type.
>
> https://stackoverflow.com/a/49673748

**Comment by marcinadd** [comment]
I'm back. Thanks for your response.
Currently I'm studying and I've much less time for this project, but it doesn't look complicated.
I will try to make a script to refactor it.

**Comment by everythings13** [comment]
Hi @FlorianKrammel/ @marcinadd , lmk if some refactoring still needs to be taken up! :)
